def generate_roadmap(syllabus_data):
    """
    Generates a study roadmap based on the syllabus data.

    Args:
        syllabus_data (dict): The syllabus data generated by syllabus.py.

    Returns:
        list: A list of dictionaries representing the roadmap steps, each with a prompt.
    """

    roadmap = []
    step_number = 1

    for unit in syllabus_data["units"]:
        for topic in unit["topics"]:
            prompt = f"""
            ## {topic['topic_title']}

            **Introduction:**
            Provide a brief introduction to the topic "{topic['topic_title']}", explaining its importance. 

            **Definition:**
            What is the definition of "{topic['topic_title']}"? 

            **Analogy:**
            Can you explain "{topic['topic_title']}" using an analogy?

            **Examples:**
            Provide 2-3 concrete examples of "{topic['topic_title']}" in action.

            **MCQ Questions:**
            Generate 3 multiple-choice questions (with 4 options each) related to "{topic['topic_title']}".

            ```json
            {{
              "introduction": "Introduction text...",
              "definition": "Definition text...",
              "analogy": "Analogy text...",
              "examples": [
                "Example 1...",
                "Example 2..."
              ],
              "mcq_questions": [
                {{
                  "question": "Question 1...",
                  "options": [
                    "Option 1...", 
                    "Option 2...",
                    "Option 3...",
                    "Option 4..."
                  ],
                  "answer": "Correct Answer..." 
                }},
                // ... more MCQ questions in the same format
              ]
            }}
            ```
            """

            roadmap.append({
                "step_number": step_number,
                "topic": topic["topic_title"],
                "prompt": prompt
            })
            step_number += 1

    return roadmap
