def generate_roadmap(syllabus_data):
    """
    Generates a study roadmap based on the syllabus data.

    Args:
        syllabus_data (dict): The syllabus data generated by syllabus.py.

    Returns:
        list: A list of dictionaries representing the roadmap steps, each with a prompt.
    """

    roadmap = []
    step_number = 1

    for unit in syllabus_data["units"]:
        for topic in unit["topics"]:
            prompt = f"""
            ## {topic['topic_title']}

            **Introduction:**
            Provide a brief introduction to the topic "{topic['topic_title']}", explaining its importance and relevance within the broader context of {syllabus_data['course_topic']}.

            **Definition:**
            What is the definition of "{topic['topic_title']}"? Provide a clear and concise definition, using simple language that a beginner can understand.

            **Analogy:**
            Can you explain "{topic['topic_title']}" using an analogy? Relate it to a real-world concept or scenario that makes it easier to grasp.

            **Examples:**
            Provide 2-3 concrete examples of "{topic['topic_title']}" in action. These examples should illustrate how the concept is applied in practice.

            **MCQ Questions:**
            Generate 3 multiple-choice questions (with 4 options each) that test the user's understanding of "{topic['topic_title']}". Include the correct answer for each question.

            **Format the output as a JSON object with the following structure:**

            ```json
            {{
              "introduction": "Introduction text",
              "definition": "Definition text",
              "analogy": "Analogy text",
              "examples": [
                "Example 1",
                "Example 2",
                // ...
              ],
              "mcq_questions": [
                {{
                  "question": "Question text",
                  "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
                  "answer": "Correct answer"
                }},
                // ... more questions
              ]
            }}
            ```
            """

            roadmap.append({
                "step_number": step_number,
                "topic": topic["topic_title"],
                "prompt": prompt
            })
            step_number += 1

    return roadmap